//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeHouseBoyaraVlas.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Sale = new HashSet<Sale>();
        }
    
        public int IdEmployee { get; set; }
        public string Name { get; set; }
        public string Surename { get; set; }
        public string Patronimyc { get; set; }
        public int IdRole { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public System.DateTime DateOfEmployment { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsMale { get; set; }
        public int IdAccount { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sale { get; set; }
    }
}
