//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeHouseBoyaraVlas.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SaleStats
    {
        public int IdSale { get; set; }
        public string employee { get; set; }
        public string customer { get; set; }
        public Nullable<System.DateTime> dateOfSale { get; set; }
        public Nullable<decimal> FullCost { get; set; }
    }
}
